version: "2.2"
services:
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - "4444:4444"   
  real_device:
    build:
      context: ./repo_docker
      dockerfile: appium.Dockerfile    
    depends_on:
      - selenium_hub
    privileged: true
    ports:
      - "4723:4723"
    volumes:
      - .android:/root/.android        
      - ./example/sample_apk:/root/tmp #pasta da APK a ser instada
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub  
  nexus_7.1.1:
    #image: budtmo/docker-android-x86-7.1.1
    build:
      context: ./repo_docker
      dockerfile: android.Dockerfile  
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub
      - real_device
    ports:
      - "6080:6080"
    volumes:
      - ./example/sample_apk:/root/tmp #pasta da APK a ser instada
      - ./.video:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true      